# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

joint_limits:
  shoulder_pan_joint:
    min_position: -2.35
    max_position: 4.72
    has_velocity_limits: true
    max_velocity: 5.2
    has_acceleration_limits: false
    max_acceleration: 1
  shoulder_lift_joint:
    min_position: -3.1415
    max_position: -1.57
    has_velocity_limits: true
    max_velocity: 5.2
    has_acceleration_limits: false
    max_acceleration: 1 
  elbow_joint:
    min_position: 0
    max_position: 2.81
    has_velocity_limits: true
    max_velocity: 5.2
    has_acceleration_limits: false
    max_acceleration: 1
  wrist_1_joint:
    min_position: -2.35
    max_position: 2.35  
    has_velocity_limits: true
    max_velocity: 5.2
    has_acceleration_limits: false
    max_acceleration: 1
  wrist_2_joint: 
    min_position: -1.57
    max_position: 3.1415     
    has_velocity_limits: true
    max_velocity: 5.2
    has_acceleration_limits: false
    max_acceleration: 1
  wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 5.2
    has_acceleration_limits: false
    max_acceleration: 1
    
  robotiq_85_left_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 0.01
    has_acceleration_limits: false
    max_acceleration: 1    
