<?xml version="1.0"?>
<robot  xmlns:xacro="http://ros.org/wiki/xacro">
	
	<xacro:macro name="mlp3240" params="prefix ">
		<xacro:property name="physical_parameters" value="${load_yaml('$(find mlp3240_description)/config/physical_params.yaml')}"/>    
		
		<material name="white">
			<color rgba="1 1 1 1"/>
		</material>        
	    
	    <link name="${prefix}base_link_gripper">
		<inertial>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<mass value="0.01"/>
			<inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
		</inertial>
		<visual>
		    <origin xyz="0 0 0" rpy="0 0 1.57" />
		    <geometry>
		        <mesh filename="package://mlp3240_description/mesh/visual/bottom.stl" scale="0.001 0.001 0.001"/>
		    </geometry>
		    <material name="black">
		        <color rgba="${61/255} ${61/255} ${61/255} 1.0"/>
		    </material>
		</visual>
	    <collision>
		  	<origin xyz="0 0 0" rpy="0 0 1.57" />
		  	<geometry>
		    	<mesh filename="package://mlp3240_description/mesh/visual/bottom.stl" scale="0.001 0.001 0.001"/>
		  	</geometry>
	    </collision>
	    </link>
	    <link name="${prefix}left">
	    	<inertial>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<mass value="0.001"/>
				<inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
			</inertial>
		<visual>
		    <origin xyz="-0.01 0 0.014" rpy="0 0 1.57" />
		    <geometry>
		        <mesh filename="package://mlp3240_description/mesh/visual/lateral.stl" scale="0.001 0.001 0.001"/>
		    </geometry>
		    <material name="black">
		        <color rgba="${61/255} ${61/255} ${61/255} 1.0"/>
		    </material>
		</visual>
	    <collision>
		  	<origin xyz="-0.01 0 0.014" rpy="0 0 1.57" />
		  	<geometry>
		    	<mesh filename="package://mlp3240_description/mesh/visual/lateral.stl" scale="0.001 0.001 0.001"/>
		  	</geometry>
	    </collision>		
	    </link>

	    <link name="${prefix}right">
	    	<inertial>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<mass value="0.001"/>
				<inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
			</inertial>
		<visual>
		    <origin xyz="0.01 0 0.014" rpy="0 0 1.57" />
		    <geometry>
		        <mesh filename="package://mlp3240_description/mesh/visual/lateral.stl" scale="0.001 0.001 0.001"/>
		    </geometry>
		    <material name="black">
		        <color rgba="${61/255} ${61/255} ${61/255} 1.0"/>
		    </material>
		</visual>
	    <collision>
			<origin xyz="0.01 0 0.014" rpy="0 0 1.57" />
		    <geometry>
		    	<mesh filename="package://mlp3240_description/mesh/visual/lateral.stl" scale="0.001 0.001 0.001"/>
		  	</geometry>
	    </collision>			
	    </link>
	    <link name="${prefix}back">
	    	<inertial>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<mass value="0.001"/>
				<inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
			</inertial>
		<visual>
		    <origin xyz="0 -0.005 0.0065" rpy="0 0 1.57" />
		    <geometry>
		        <mesh filename="package://mlp3240_description/mesh/visual/front.stl" scale="0.001 0.001 0.001"/>
		    </geometry>
		    <material name="black">
		        <color rgba="${61/255} ${61/255} ${61/255} 1.0"/>
		    </material>
		</visual>
		<collision>
			<origin xyz="0 -0.005 0.0065" rpy="0 0 1.57" />
		  	<geometry>
		    	<mesh filename="package://mlp3240_description/mesh/visual/front.stl" scale="0.001 0.001 0.001"/>
		 	</geometry>
	    </collision>	
	    </link>
	    <link name="${prefix}front">
	    	<inertial>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<mass value="0.001"/>
				<inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
			</inertial>
		<visual>
		    <origin xyz="0 0.005 0.0065" rpy="0 0 1.57" />
		    <geometry>
		        <mesh filename="package://mlp3240_description/mesh/visual/front_w_box.stl" scale="0.001 0.001 0.001"/>
		    </geometry>
		    <material name="black">
		        <color rgba="${61/255} ${61/255} ${61/255} 1.0"/>
		    </material>
			</visual>
			<collision>
				<origin xyz="0 0.005 0.0065" rpy="0 0 1.57" />
				<geometry>
					<mesh filename="package://mlp3240_description/mesh/visual/front_w_box.stl" scale="0.001 0.001 0.001"/>
				</geometry>
			</collision>			
	    </link>
	    <link name="${prefix}top">
	    	<inertial>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<mass value="0.001"/>
				<inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
			</inertial>
			<visual>
				<origin xyz="0 0 0.006" rpy="0 0 1.57" />
				<geometry>
					<mesh filename="package://mlp3240_description/mesh/visual/top.stl" scale="0.001 0.001 0.001"/>
				</geometry>
				<material name="black">
					<color rgba="${61/255} ${61/255} ${61/255} 1.0"/>
				</material>
			</visual>
			<collision>
				<origin xyz="0 0 0.006" rpy="0 0 1.57" />
				<geometry>
					<mesh filename="package://mlp3240_description/mesh/visual/top.stl" scale="0.001 0.001 0.001"/>
				</geometry>
			</collision>		
	    </link>
	    
	    <link name="${prefix}finger1">
	    	<inertial>
				<origin xyz="0.015 0 0.015" rpy="0 0 0" />
				<mass value="0.1"/>
				<inertia ixx="0.000015417" ixy="0.0" ixz="0.0" iyy="0.000010232" iyz="0.0" izz="0.000005232"/>
			</inertial>
			<visual>
				<origin xyz="0.015 0 0.001" rpy="0 0 1.57" />
				<geometry>
					<mesh filename="package://mlp3240_description/mesh/visual/finger_1.stl" scale="0.001 0.001 0.001"/>
				</geometry>
				<material name="white"/>
			</visual>
			<collision>
				<origin xyz="0.015 0 0.015" rpy="0 0 0" />
				<geometry>
        			<box size="0.0017 0.025 0.035" />
		  		</geometry>
			</collision>
			<!-- bad mesh causes bad physics while collision
			<collision>
				<origin xyz="0.015 0 0.001" rpy="0 0 1.57" />
				<geometry>
					<mesh filename="package://mlp3240_description/mesh/visual/finger_1.stl" scale="0.001 0.001 0.001"/>
				</geometry>
			</collision>	
			-->	
	    </link>
	    <link name="${prefix}finger2">
	    	<inertial>
				<origin xyz="0.015 0 0.015" rpy="0 0 0" />
				<mass value="0.1"/>
				<inertia ixx="0.000015417" ixy="0.0" ixz="0.0" iyy="0.000010232" iyz="0.0" izz="0.000005232"/>
			</inertial>
			<visual>
				<origin xyz="0.015 0 0.0015" rpy="0 0 1.57" />
				<geometry>
					<mesh filename="package://mlp3240_description/mesh/visual/finger_2.stl" scale="0.001 0.001 0.001"/>
				</geometry>
				<material name="white"/>
			</visual>
			<collision>
				<origin xyz="0.015 0 0.015" rpy="0 0 0" />
				<geometry>
        			<box size="0.0017 0.025 0.035" />
		  		</geometry>
				<!-- bad mesh causes bad physics while collision
				<origin xyz="0.015 0 0.001" rpy="0 0 1.57" />
				<geometry>
		    		<mesh filename="package://mlp3240_description/mesh/visual/finger_2.stl" scale="0.001 0.001 0.001"/>
		  		</geometry>
				-->
	    	</collision>
	    </link>

		<joint name="${prefix}base_to_left_joint" type="fixed">
			<parent link="${prefix}base_link_gripper"/>
			<child link="${prefix}left"/>
			<origin xyz="${physical_parameters['base_x']/2} 0 0.015" rpy='0 0 0'/>
		</joint>
		<joint name="${prefix}base_to_right_joint" type="fixed">
			<parent link="${prefix}base_link_gripper"/>
			<child link="${prefix}right"/>
			<origin xyz="-${physical_parameters['base_x']/2} 0 0.015" rpy='0 0 0'/>
		</joint>
		<joint name="${prefix}base_to_front_joint" type="fixed">
			<parent link="${prefix}base_link_gripper"/>
			<child link="${prefix}front"/>
			<origin xyz="0 ${physical_parameters['base_y']/2} 0.015" rpy='0 0 0'/>
		</joint>
		<joint name="${prefix}base_to_back_joint" type="fixed">
			<parent link="${prefix}base_link_gripper"/>
			<child link="${prefix}back"/>
			<origin xyz="0 -${physical_parameters['base_y']/2} 0.015" rpy='0 0 0'/>
		</joint>
		<joint name="${prefix}left_to_top_joint" type="fixed">
			<parent link="${prefix}left"/>
			<child link="${prefix}top"/>
			<origin xyz="-${physical_parameters['left_y']} 0 0.03" rpy='0 0 0'/>
		</joint>
		<joint name="${prefix}top_to_finger1_joint" type="prismatic">
			<parent link="${prefix}top"/>
			<child link="${prefix}finger1"/>
			<origin xyz="${physical_parameters['top_x']/2 - 0.005} 0 0.0211" rpy='0 0 -3.14'/>
			<limit upper="0.0336" lower="0.0" effort="300" velocity="1"/>
		</joint>
		<joint name="${prefix}top_to_finger2_joint" type="prismatic">
			<parent link="${prefix}top"/>
			<child link="${prefix}finger2"/>
			<origin xyz="-${physical_parameters['top_x']/2 - 0.005} 0 0.021" rpy='0 0 0'/>
			<limit upper="0.0336" lower="0.0" effort="300" velocity="1"/>
			<mimic joint="${prefix}top_to_finger1_joint" multiplier="1.0" offset="0.0" />
		</joint>
		
		<!-- Transmission for ROS control -->
		<transmission name="${prefix}top_to_finger1_joint_trans">
			<type>transmission_interface/SimpleTransmission</type>
			<joint name="${prefix}top_to_finger1_joint">
				<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
			</joint>
			<actuator name="${prefix}top_to_finger1_joint_motor">
				<mechanicalReduction>1</mechanicalReduction>
				<hardwareInterface>hardware_interface/EfforJointInterface</hardwareInterface> 
			</actuator>
		</transmission>    

		<!-- Mimic joints -->
		<gazebo>
			<plugin filename="libgazebo_mimic_joint_plugin.so" name="${prefix}mimic_top_to_finger1_joint">
				<joint>${prefix}top_to_finger1_joint</joint>
				<mimicJoint>${prefix}top_to_finger2_joint</mimicJoint>
			</plugin>
		</gazebo>

		<!-- Improve grasping physics -->
		<gazebo reference="${prefix}finger1">
			<collision name="finger1_collision">
			<surface>
				<friction>
					<torsional>
						<coefficient>10.0</coefficient>
						<use_patch_radius>true</use_patch_radius>
						<patch_radius>0.05</patch_radius>
					</torsional>
				</friction>
				<contact>
					<poissons_ratio>0.5</poissons_ratio>
					<elastic_modulus>1e8</elastic_modulus>
				</contact>
			</surface>
			</collision>
			<kp>1000000.0</kp>
			<kd>10.0</kd>
			<mu1>100.0</mu1>
			<mu2>100.0</mu2>
			<minDepth>0.001</minDepth>
			<maxVel>1000</maxVel>
		</gazebo>
		<gazebo reference="${prefix}finger2">
			<collision name="finger2_collision">
			<surface>
				<friction>
					<torsional>
						<coefficient>10.0</coefficient>
						<use_patch_radius>true</use_patch_radius>
						<patch_radius>0.05</patch_radius>
					</torsional>
				</friction>
				<contact>
					<poissons_ratio>0.5</poissons_ratio>
					<elastic_modulus>1e8</elastic_modulus>
				</contact>
			</surface>
			</collision>
			<kp>1000000.0</kp>
			<kd>10.0</kd>
			<mu1>100.0</mu1>
			<mu2>100.0</mu2>
			<minDepth>0.001</minDepth>
			<maxVel>1000</maxVel>
		</gazebo>
		
		<gazebo>
	  		<plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so" />
    	</gazebo>
		
		<!-- to get grasping properly works on Gazebo -->	
		
		<gazebo>
			<plugin name="gazebo_grasp_fix" filename="libgazebo_grasp_fix.so">
				<arm>
					<arm_name>robot_arm</arm_name>
					<palm_link>wrist_3_link</palm_link>
					<gripper_link>finger1</gripper_link>
					<gripper_link>finger2</gripper_link>
				</arm>
				<forces_angle_tolerance>100</forces_angle_tolerance>
				<update_rate>10</update_rate>
				<grip_count_threshold>1</grip_count_threshold>
				<max_grip_count>10</max_grip_count>
				<release_tolerance>0.001</release_tolerance>
				<disable_collisions_on_attach>true</disable_collisions_on_attach>
				<contact_topic>__default_topic__</contact_topic>
			</plugin>
		</gazebo>	
		
		<!--
		<gazebo>
			<gripper name="grasping">
				<grasp_check>
					<attach_steps>1</attach_steps>
					<detach_steps>10</detach_steps>
					<min_contact_count>1</min_contact_count>
				</grasp_check>
				<palm_link>wrist_3_link</palm_link>
				<gripper_link>finger1</gripper_link>
				<gripper_link>finger2</gripper_link>
			</gripper>
		</gazebo>
		-->

	</xacro:macro>
</robot>
